name: Crash Report
description: Report a crash that occurred while playing the game.
labels: ["crash"]
title: "[CRASH REPORT] "
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        - label: I have checked the Issues/Discussions pages to see if my issue has already been reported
        - label: I have properly named my issue

  - type: markdown
    attributes:
      value: "## Describe the crash."

  - type: textarea
    attributes:
      label: Description
      description: Include screenshots or videos of the crash happening. Provide as much detail as you can.
      placeholder: Describe the crash here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What steps can other people take to reliably trigger this crash?
      placeholder: 1. Open Codename Engine
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash logs
      description: These can be found in the logs folder where Funkin.exe is.
      placeholder: Upload your logs here...
    validations:
      required: true
